### ISSUE TITLE
want a pacman game?

### ISSUE THREAD

**Issue by staktrace** [NeilFraser/beaver-games#5]
There's a pacman game at https://github.com/daleharvey/pacman which I think would suit beaver games. For my kid I modified it to remove the ghosts, so it's just dot-eating. I'm happy to make a PR if you want to include it. I can add a dropdown for easy/medium/hard levels. (easy = no ghosts at all, medium = ghosts that don't move, hard = regular pacman)

**Comment by staktrace** [comment]
https://staktrace.github.io/pacman/index.html is the "hard" version (i.e. regular pacman)

**Comment by NeilFraser** [comment]
Ooh, that's nice.  I would be very concerned about Namco though.  They have a long history of taking legal actions.  For example:
https://en.scratch-wiki.info/wiki/Removed_Pac-Man_Project

**Comment by staktrace** [comment]
Ah fair enough. Probably not worth the risk then. At any rate, thanks for making beaver games! Very much in line with what I've been looking for my kids 😄
